name: Maven build

on: ['push']

jobs:
  build:
    name: Build Infobip Java API Client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -U

  snyk:
    name: Snyk Code Coverage
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running Snyk Code Coverage
        uses: snyk/actions/maven-3-jdk-11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
                --severity-threshold=high|critical

      - name: Check snyk
        run: cat snyk.sarif

      - name: Check Snyk Report
        run: |
          high_critical=$(cat snyk.sarif | jq '.runs[].tool.driver.rules[].shortDescription.text | select(test("High|Critical"))')
          if [[ -z $high_critical ]]; then
            echo "No high or critical vulnerabilities found."
          else
            echo "High or critical vulnerabilities found!"
            exit 1
          fi
      - name: Upload Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif


  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=juhandergod_github-test -Dsonar.host.url=https://sonarcloud.io
