name: Maven publish

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      username:
        description: 'MAVEN_USERNAME'
        required: true
      password:
        description: 'MAVEN_PASSWORD'
        required: true
      release-version:
        description: 'RELEASE_VERSION'
        required: true

jobs:
  mvn-release:
    name: Maven release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false
      - name: Upload changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release version ${{ github.event.inputs.release-version }}
  release-on-push:
    name: Create Release
    needs: mvn-release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
#      - name: Get Changelog Entry
#        id: changelog_reader
#        uses: mindsers/changelog-reader-action@v2
#        with:
#          validation_level: warn
#          version: ${{ github.event.inputs.release-version }}
#          path: ./CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: ${{ github.event.inputs.release-version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
  publish:
    runs-on: ubuntu-latest
    needs: release-on-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ github.event.inputs.username }}
          MAVEN_PASSWORD: ${{ github.event.inputs.password }}
