name: Maven publish

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      username:
        description: 'MAVEN_USERNAME'
      password:
        description: 'MAVEN_PASSWORD'
      release-version:
        description: 'RELEASE_VERSION'

jobs:
  mvn-release:
    name: Maven release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false
      - name: Upload changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prepare release ${{ github.event.inputs.release-version }}
  release-on-push:
    name: Create Release
    needs: mvn-release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: ${{ github.event.inputs.release-version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  publish:
    runs-on: ubuntu-latest
    needs: release-on-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ github.event.inputs.username }}
          MAVEN_PASSWORD: ${{ github.event.inputs.password }}
