name: Maven publish

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      username:
        description: 'MAVEN_USERNAME'
      password:
        description: 'MAVEN_PASSWORD'
      release-version:
        type: choice
        description: Release type
        options:
          - no-release
          - patch
          - minor
          - major

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ github.event.inputs.release-version }}
  publish:
    runs-on: ubuntu-latest
    needs: release-on-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ github.event.inputs.username }}
          MAVEN_PASSWORD: ${{ github.event.inputs.password }}
